spring:
  application:
    name: "simple-orders-kafka-streams"

  kafka:
    bootstrap-servers: localhost:9092

    streams:
      application-id: ${spring.application.name}
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
        # This is the default: log, fail and stop processing records (stop stream)
        default.deserialization.exception.handler: org.apache.kafka.streams.errors.LogAndFailExceptionHandler

management:
  endpoints:
    web:
      exposure:
        include: "*"